"""Projects Table Update

Revision ID: f61d54d67775
Revises: 4bb65d7f6e78
Create Date: 2023-08-03 12:28:28.421046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f61d54d67775'
down_revision = '4bb65d7f6e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
